from app.schemas.sec_rag import SecRiskAnswer
from app.exceptions.ai_exceptions import AIValidationException


def validate_citations(
        answer: SecRiskAnswer,
        search_results: list[dict]
) -> None:

    # All chunk IDs that were actually retrieved
    valid_chunk_ids = {
        result["chunk_index"]
        for result in search_results
    }

    # Validate every claim generated by the LLM
    for claim in answer.claims:

        # Every claim must have at least one citation
        if not claim.source_chunk_ids:
            raise AIValidationException(
                message=(
                    f"AI response contains a claim without citation: "
                    f"{claim.claim}"
                )
            )

        # Every cited chunk must exist in the retrieval results
        for chunk_id in claim.source_chunk_ids:

            if chunk_id not in valid_chunk_ids:
                raise AIValidationException(
                    message=(
                        f"AI response referenced CHUNK {chunk_id}, "
                        f"but that chunk was not retrieved."
                    )
                )